### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by zc1616** [jmcasebeer/cost_aware_enhancement#1]
Hello! Thank for your open source code! 
I have some question about how to select the microphone when you test the model?
In another way, how do your Data-request mechanism work when we test ?

**Comment by jmcasebeer** [comment]
Thank you for the question!

The data-request mechanism works identically at train and test time. You can find details of the mechanism in algorithm 1 of our [paper](https://arxiv.org/abs/2011.07348).

Hope this helps!
